application: talklikeapp
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /admin
  script: main.py
  login: admin 

- url: /admin/.*
  script: main.py
  login: admin 

- url: /.*
  script: main.py
